#!/usr/sbin/nft -f

flush ruleset

table inet filter {
  chain input {
    type filter hook input priority filter; policy drop;
    iif "lo" accept
    meta l4proto ipv6-icmp accept
    meta l4proto      icmp accept
    udp dport { 67, 68, 546 } counter accept comment "dhcp"
    ct state vmap { established : accept, related : accept, invalid : drop }
    ip6 saddr { 2001:67c:828::/48 } tcp dport { 22 } counter accept
    ip6 saddr { 2001:67c:828::/48 } tcp dport { 8000 } counter accept comment "llm api"
  }
  chain forward {
    type filter hook forward priority filter; policy drop;
    counter log
  }
  chain output {
    type filter hook output priority filter; policy accept;
  }
}
